services:
  db:
    image: postgres:15-alpine
    container_name: semana4-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata4:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: semana4-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 80
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: admin
      DB_NAME: db
      DB_PORT: 5432
      JWT_SECRET: secretkey
    ports:
      - "80:80"

volumes:
  pgdata4:
